contactbook/models.py
from django.db import models

class Contact(models.Model):  
    cid = models.CharField(max_length=20)  
    cname = models.CharField(max_length=100)  
    cemail = models.EmailField()  
    ccontact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "contact"  

contactbook/forms.py
from django import forms  
from contact.models import Contact  
class ContactForm(forms.ModelForm):  
    class Meta:  
        model = Contact  
        fields = "__all__"  

contactbook/views.py
from django.shortcuts import render, redirect  
from contact.forms import contactForm  
from contact.models import contact  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = contactForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = contactForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    contacts = contact.objects.all()  
    return render(request,"show.html",{'contacts':contacts})  
def edit(request, id):  
    contact = contact.objects.get(id=id)  
    return render(request,'edit.html', {'contact':contact})  
def update(request, id):  
    contact = contact.objects.get(id=id)  
    form = contactForm(request.POST, instance = contact)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'contact': contact})  
def destroy(request, id):  
    contact = contact.objects.get(id=id)  
    contact.delete()  
    return redirect("/show")

contactbook/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{contact.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cid" id="id_cid" required maxlength="20" value="{{ contact.cid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cname" id="id_cname" required maxlength="100" value="{{ contact.cname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="cemail" id="id_cemail" required maxlength="254" value="{{ contact.cemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ccontact" id="id_ccontact" required maxlength="15" value="{{ contact.ccontact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

contactbook/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/cont">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Id:</label>  
    <div class="col-sm-4">  
      {{ form.cid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Name:</label>  
    <div class="col-sm-4">  
      {{ form.cname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Email:</label>  
    <div class="col-sm-4">  
      {{ form.cemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Contact:</label>  
    <div class="col-sm-4">  
      {{ form.ccontact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

contactbook/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Contact Records</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Contact ID</th>  
        <th>Contact Name</th>  
        <th>Contact Email</th>  
        <th>Contact Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for contact in contacts %}  
    <tr>  
        <td>{{ contact.cid }}</td>  
        <td>{{ contact.cname }}</td>  
        <td>{{ contact.cemail }}</td>  
        <td>{{ contact.ccontact }}</td>  
        <td>  
            <a href="/edit/{{ contact.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ contact.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>